services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"   # optional: expose for debugging
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: /graphql   # same-origin; nginx proxies to server
    ports:
      - "8080:80"
    depends_on:
      - server
